/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_telegie_mainserver_LibrgbdJNI */

#ifndef _Included_com_telegie_mainserver_LibrgbdJNI
#define _Included_com_telegie_mainserver_LibrgbdJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    nativeGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_telegie_mainserver_LibrgbdJNI_nativeGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    nativeCreateFileParser
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_telegie_mainserver_LibrgbdJNI_nativeCreateFileParser
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    nativeDeleteFileParser
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_telegie_mainserver_LibrgbdJNI_nativeDeleteFileParser
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    nativeGetCoverPngBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_telegie_mainserver_LibrgbdJNI_nativeGetCoverPngBytes
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
