/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_telegie_mainserver_LibrgbdJNI */

#ifndef _Included_com_telegie_mainserver_LibrgbdJNI
#define _Included_com_telegie_mainserver_LibrgbdJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_telegie_mainserver_LibrgbdJNI_sayHello
  (JNIEnv *, jclass);

/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    createFileParser
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_telegie_mainserver_LibrgbdJNI_createFileParser
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    getCoverPngBytes
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_telegie_mainserver_LibrgbdJNI_getCoverPngBytes
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
