/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_telegie_mainserver_LibrgbdJNI */

#ifndef _Included_com_telegie_mainserver_LibrgbdJNI
#define _Included_com_telegie_mainserver_LibrgbdJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_telegie_mainserver_LibrgbdJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT int JNICALL Java_com_telegie_mainserver_LibrgbdJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
